name: Build Website

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build Website
      run: bundle && bundle exec jekyll build
    - run: "echo `date` >>index.md"
    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v6
      with:
        add: '.'
        author_name: Github Action
        author_email: bascule@gmail.com
        message: 'Update Website'
        push: true
        token: ${{ secrets.GITHUB_TOKEN }}
