name: Build Website

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: jonasbb/rustsec.github.io
        ssh-key: ${{ secrets.RUSTSEC_DEPLOYKEY }}
      
    - name: Cache cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: rustsec-admin-v0.3.3

    - name: Install rustsec-admin
      run: |
        if [ ! -f $HOME/.cargo/bin/rustsec-admin ]; then
            cargo install rustsec-admin --vers 0.3.3
        fi
      
    - run: "echo `date` >>index.md"
      
    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v6
      with:
        add: '.'
        author_name: Github Action
        author_email: bascule@gmail.com
        message: 'Update Website'
        push: true

        token: ${{ secrets.GITHUB_TOKEN }}
